### ISSUE TITLE
RobustPerception prometheus packages

### ISSUE THREAD

**Issue by zerthimon** [RobustPerception/demo_prometheus_ansible#1]
Hi,

I'm not sure if this is the right place to report repository issues, but anyway here goes.
I'm trying to use your repo and packages with ubuntu Xenial and found out that the names of packages differ. Would you consider changing packages names to match the names of official ubuntu packages eg.:
node-exporter -> prometheus-node-exporter
pushgateway -> prometheus-pushgateway
alertmanager -> prometheus-alertmanager

Currently, when your repo is enabled on xenial, the search for prometheus results in:

```
ring01:~# apt-cache search prometheus
cadvisor - analyze resource usage and performance characteristics of running containers
golang-github-google-cadvisor-dev - analyze resource usage and performance of running containers
golang-github-prometheus-common-dev - Common libraries for Prometheus components
golang-github-prometheus-log-dev - Logging library for Prometheus's Go-based components
golang-prometheus-client-dev - Prometheus instrumentation library for Go applications
prometheus-cli - Prometheus command line interface
prometheus-node-exporter - Prometheus exporter for machine metrics
prometheus-pushgateway - Prometheus exporter for ephemereal jobs
python-prometheus-client - Python 2 client for the Prometheus monitoring system
python3-prometheus-client - Python 3 client for the Prometheus monitoring system
prometheus-mysqld-exporter - Prometheus exporter for MySQL server.
alertmanager - Alertmanager for Prometheus monitoring system
node-exporter - Prometheus exporter agent for machine metrics
prometheus - Prometheus monitoring system and time series database
pushgateway - Pushgateway for Prometheus monitoring system
```

**Comment by brian-brazil** [comment]
Our packages are nightlies that are not produced by Debian upstream, I'm not sure we should be clashing on the package names given the different sources and types of packages involved.

If you're looking for Prometheus packages for production use. the ones from Debian are generally a better idea.

**Comment by zerthimon** [comment]
I'm looking for the maintained repo with latest versions of Prometheus Ubuntu packages but there seems to be none. Your repo is the only one i could find that has all the packages I need.

**Comment by brian-brazil** [comment]
You should be able to pull debs straight from Debian.

**Comment by zerthimon** [comment]
Debian doesn't have alertmanager package

**Comment by brian-brazil** [comment]
Hmm, I'd thought there was. @TheTincho is the best person to talk to about Debian packaging.

The Robust Perception nightlies are intended only really for demos and experimentation.

**Comment by zerthimon** [comment]
@brian-brazil thanks. Closing.

**Comment by NightTsarina** [comment]
Hey. Yes, I was supposed to prepare the alert manager a couple of months ago, and instead started working on backporting the whole stack to jessie. Sorry about that, I will try to prepare the alertmanager asap.
The other main components (prometheus, prometheus-cli, node-exporter) are all present and current in Debian.

**Comment by zerthimon** [comment]
Hey @TheTincho thanks a lot!

**Comment by zerthimon** [comment]
@brian-brazil are deb sources of your nightly Prometheus packages publicly available ?

**Comment by brian-brazil** [comment]
No, the deb sources aren't available.
