### ISSUE TITLE
example config regarding memory chunks and local retention time

### ISSUE THREAD

**Issue by Vannevelj** [RobustPerception/demo_prometheus_ansible#2]
I had a look through the main.yml file and had some questions with a few configuration aspects.

```
 # Only 1GB of RAM
 DAEMON_ARGS="$DAEMON_ARGS -storage.local.memory-chunks=51200"
 DAEMON_ARGS="$DAEMON_ARGS -storage.local.max-chunks-to-persist=51200"
```

What is the relationship between memory chunks and RAM? Is there a fixed size to a chunk?

```
# Keep 6 months of data
DAEMON_ARGS="$DAEMON_ARGS -storage.local.retention=744h"
```

744h equals 31 days -- how does this result in keeping 6 months of data?

**Comment by brian-brazil** [comment]
> What is the relationship between memory chunks and RAM? Is there a fixed size to a chunk?

Chunks are 1kB.

> 744h equals 31 days -- how does this result in keeping 6 months of data?

The comment was out of date, I've updated it.

**Comment by Vannevelj** [comment]
If a chunk is 1kB and you have 51200 chunks in memory that's only 50MB. What is the math here to get up to 1GB?

**Comment by brian-brazil** [comment]
There's overhead on top of that, the base use of Prometheus and the other binaries running on the machine.

**Comment by Vannevelj** [comment]
That's a lot of external factors: 950MB vs 50MB. Is there any guidance on how to decide these numbers or is it a matter of playing around with it and see what works? If I recall correctly, the default value for this setting is 20 times higher than this.

**Comment by brian-brazil** [comment]
The defaults are for a Prometheus which has 4GB to itself. This demo is squeezing 4 processes into 1GB of RAM.

If you are trying to get things under 1GB, then playing around with your particular setup is probably best.

**Comment by Vannevelj** [comment]
Gotcha. That clears these things up, cheers. I'll use that to properly calibrate our setup.
