### ISSUE TITLE
Possible issue with failure cases in the cronjob here?

### ISSUE THREAD

**Issue by mpursley** [RobustPerception/demo_prometheus_ansible#4]
```      */5 * * * * root du -sb /var/log /var/cache/apt /var/lib/prometheus | sed -ne 's/^\([0-9]\+\)\t\(.*\)$/node_directory_size_bytes{directory="\2"} \1/p' > /var/lib/node_exporter/textfile_collector/directory_size.prom.$$ && mv /var/lib/node_exporter/textfile_collector/directory_size.prom.$$ /var/lib/node_exporter/textfile_collector/directory_size.prom```

https://github.com/RobustPerception/demo_prometheus_ansible/blob/e06353848385488ac339fca5ca5be969e1a984a9/roles/prometheus/tasks/main.yml#L97

@brian-brazil  One issue here is that the '&&' will only fail if the 'sed' command fails, and not if the 'du' command fails... e.g.

```
prometheus1 ~ # du -sb /var/lib/prometheus | sed -ne 's/^\([0-9]\+\)\t\(.*\)$/node_textfile_directory_size_bytes{directory="\2"} \1/p' && echo WORKED
node_textfile_directory_size_bytes{directory="/var/lib/prometheus"} 80169933421
WORKED

prometheus1 ~ # du -sb /srv/prometheus_missing_dir | sed -ne 's/^\([0-9]\+\)\t\(.*\)$/node_textfile_directory_size_bytes{directory="\2"} \1/p' && echo WORKED
du: cannot access '/var/lib/prometheus_missing_dir': No such file or directory
WORKED  ## this worked because the 'sed' command succeeded, even though the 'du' command failed
```

You might be able to resolve this by wrapping the commands into braces to invoke them together into a sub-shell?  But, In cases like this, I think it would be better to recommend using a small 'wrapper' shell script for cron to execute, rather then trying to squeeze all the logic into one cronjob line?

If that sounds reasonable, I could work on a PR to update this playbook to correct this issue.

**Comment by brian-brazil** [comment]
This is intended to be a quick simple example, so I'd prefer not to over-complicate it.

**Comment by mpursley** [comment]
Ok, sounds good.  Thanks @brian-brazil
